# Generated by Django 5.1.7 on 2025-04-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('type', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], max_length=10)),
                ('created_by', models.IntegerField()),
                ('goal', models.CharField(choices=[('weight loss', 'Weight Loss'), ('muscle building', 'Muscle Building'), ('balanced health', 'Balanced Health'), ('weight gaining', 'Weight Gaining')], max_length=20)),
            ],
        ),
    ]
