# Generated by Django 5.1.7 on 2025-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(),
        ),
    ]
