# Generated by Django 5.1.7 on 2025-04-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_meal_carbs_alter_meal_fat_alter_meal_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='goal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='meal',
            table='meals',
        ),
    ]
